### ISSUE TITLE
env declared in cc_binary is ignored by itest

### ISSUE THREAD

**Issue by peakschris** [dzbarsky/rules_itest#25]
It appears that any env values declared in a cc_binary are silently ignored when running via itest_service. The itest service is also defining an env map but for different values.

```
cc_binary(
    name = "binary"
    ...
    env = {"ENV1": "VALUE"},
)

itest_service(
    name = "binary_itest",
    exe = "binary",
    env = {"ENV2", "VALUE"},
)
```

`bazel run //:binary_itest` does not pass ENV1 to binary.

**Comment by dzbarsky** [comment]
Good catch, we were already merging the `env` [for tests](https://github.com/dzbarsky/rules_itest/blob/3b322bee4205f30cc7b94cdb7f6e97f057700233/private/itest.bzl#L322-L328), but not for binaries. I just pushed https://github.com/dzbarsky/rules_itest/commit/9572fa97380b6cd78a186179858f8aa434f0d726 to fix this, but unfortunately this will not work for `sh_binary` because it doesn't provide the `RunEnvironmentInfo` provider. I did add a test verifying that cc_binary works, so hopefull you should be good to go!

**Comment by peakschris** [comment]
Awesome, thanks!
